#!/usr/bin/env bash
# Launch a local Chrome instance with --remote-debugging-port so Hermes can
# attach via `/browser connect` and drive it through CDP. Used by skills that
# need to operate on the user's logged-in session (e.g. instagram-kol-discovery
# in `browser_mode: local-chrome`).
#
# Usage:
#   ./start-debug-chrome.sh                # start (or reuse) debug Chrome + write env file + self-check
#   ./start-debug-chrome.sh status         # report port, env file presence, exit IP
#   ./start-debug-chrome.sh stop           # kill the debug Chrome, remove env file
#   ./start-debug-chrome.sh restart        # stop + start
#   ./start-debug-chrome.sh clean          # stop + wipe the isolated profile dir + env file
#   ./start-debug-chrome.sh export         # echo `export BROWSER_CDP_URL=...` for `eval "$(...)"`
#
# Overrides (env):
#   DEBUG_CHROME_PORT          default 9222
#   DEBUG_CHROME_PROFILE_DIR   default $HOME/.hermes/local-chrome-debug-profile
#   DEBUG_CHROME_BIN           default macOS Google Chrome path
#   DEBUG_CHROME_ENV_FILE      default $HOME/.hermes/local-chrome-debug.env
#   HERMES_HOME                default $HOME/.hermes  (where ~/.hermes/.env lives)
#
# Why two env files:
# - $HERMES_HOME/.env is the dotenv hermes auto-loads on every process start
#   (run_agent.py / hermes-gateway / hermes CLI). Upserting BROWSER_CDP_URL
#   into it means a single `restart your gateway` is the last manual step.
# - $DEBUG_CHROME_ENV_FILE is a standalone, sourceable file for ad-hoc shells
#   (`source ...env`, `eval "$(./... export)"`). Useful when you don't want
#   to touch the shared hermes dotenv.

set -euo pipefail

PORT="${DEBUG_CHROME_PORT:-9222}"
PROFILE_DIR="${DEBUG_CHROME_PROFILE_DIR:-$HOME/.hermes/local-chrome-debug-profile}"
CHROME_BIN="${DEBUG_CHROME_BIN:-/Applications/Google Chrome.app/Contents/MacOS/Google Chrome}"
ENV_FILE="${DEBUG_CHROME_ENV_FILE:-$HOME/.hermes/local-chrome-debug.env}"
HERMES_HOME_DIR="${HERMES_HOME:-$HOME/.hermes}"
HERMES_DOTENV="$HERMES_HOME_DIR/.env"

# Resolve which profile's .env hermes will actually load. When
# ~/.hermes/active_profile names a non-default profile (or the user passes
# `--profile X` on the gateway command), HERMES_HOME is redirected to
# ~/.hermes/profiles/<profile>/ and that profile's .env is the authoritative
# one. We always also write the top-level ~/.hermes/.env as a fallback.
resolve_target_dotenvs() {
  # Echoes one path per line.
  printf '%s\n' "$HERMES_DOTENV"
  local active_file="$HERMES_HOME_DIR/active_profile"
  [[ -f "$active_file" ]] || return 0
  local profile
  profile="$(tr -d '\n\r \t' < "$active_file" 2>/dev/null || true)"
  if [[ -z "$profile" || "$profile" == "default" ]]; then
    return 0
  fi
  local profile_dir="$HERMES_HOME_DIR/profiles/$profile"
  if [[ -d "$profile_dir" ]]; then
    printf '%s\n' "$profile_dir/.env"
  fi
}

log()  { printf '\033[1;32m[debug-chrome]\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m[debug-chrome]\033[0m %s\n' "$*" >&2; }
die()  { printf '\033[1;31m[debug-chrome]\033[0m %s\n' "$*" >&2; exit 1; }

port_pids() {
  # macOS / Linux with lsof. The script targets macOS per the plan.
  if command -v lsof >/dev/null; then
    lsof -tiTCP:"$PORT" -sTCP:LISTEN 2>/dev/null || true
  else
    warn "lsof not found; cannot inspect port $PORT"
  fi
}

is_debug_chrome_ready() {
  curl -fsS -m 2 "http://127.0.0.1:$PORT/json/version" >/dev/null 2>&1
}

# Fetch the live webSocketDebuggerUrl from the running Chrome.
# Echoes the ws://... URL on success; empty + nonzero exit on failure.
fetch_cdp_ws_url() {
  local body url
  if ! body="$(curl -fsS -m 4 "http://127.0.0.1:$PORT/json/version" 2>/dev/null)"; then
    return 1
  fi
  url="$(printf '%s' "$body" | python3 -c 'import json,sys;d=json.load(sys.stdin);print(d.get("webSocketDebuggerUrl",""))' 2>/dev/null || true)"
  [[ -n "$url" ]] || return 1
  printf '%s\n' "$url"
}

# Write the BROWSER_CDP_URL line to the sourceable dotenv file.
# Caller is responsible for ensuring Chrome is ready first.
write_env_file() {
  local url
  if ! url="$(fetch_cdp_ws_url)"; then
    warn "could not fetch webSocketDebuggerUrl from http://127.0.0.1:$PORT/json/version"
    return 1
  fi
  mkdir -p "$(dirname "$ENV_FILE")"
  {
    printf '# Auto-generated by start-debug-chrome.sh on %s\n' "$(date '+%Y-%m-%d %H:%M:%S')"
    printf '# Source this BEFORE launching the hermes API gateway:\n'
    printf '#     source %q\n' "$ENV_FILE"
    printf 'export BROWSER_CDP_URL=%q\n' "$url"
  } > "$ENV_FILE"
  log "wrote $ENV_FILE"
  log "  -> BROWSER_CDP_URL=$url"
  # Also push into the hermes auto-loaded dotenv so any newly started hermes
  # process picks it up without needing source/eval.
  upsert_hermes_dotenv "$url" || warn "failed to upsert into $HERMES_DOTENV"
}

# Remove the dotenv so a stale CDP URL can't be sourced after stop/clean.
remove_env_file() {
  if [[ -f "$ENV_FILE" ]]; then
    warn "removing stale $ENV_FILE"
    rm -f "$ENV_FILE"
  fi
  remove_hermes_dotenv_entry
}

# Upsert `BROWSER_CDP_URL=<url>` into every dotenv hermes might auto-load
# (top-level + active profile, see resolve_target_dotenvs). Idempotent: strips
# any existing BROWSER_CDP_URL= or `export BROWSER_CDP_URL=` line and appends
# one fresh line. Preserves all other content.
upsert_hermes_dotenv() {
  local url="$1"
  [[ -n "$url" ]] || { warn "upsert_hermes_dotenv: empty url, skipping"; return 1; }
  local target
  while IFS= read -r target; do
    [[ -n "$target" ]] || continue
    mkdir -p "$(dirname "$target")"
    if [[ ! -f "$target" ]]; then
      touch "$target"
      chmod 600 "$target"
    fi
    HERMES_DOTENV_TARGET="$target" CDP_URL="$url" python3 - <<'PY'
import os, pathlib, re
path = pathlib.Path(os.environ["HERMES_DOTENV_TARGET"])
url = os.environ["CDP_URL"]
text = path.read_text(encoding="utf-8", errors="replace") if path.exists() else ""
pattern = re.compile(r'^\s*(?:export\s+)?BROWSER_CDP_URL\s*=.*$', re.MULTILINE)
text = pattern.sub('', text)
text = re.sub(r'\n{3,}', '\n\n', text).rstrip() + '\n'
text += f'BROWSER_CDP_URL={url}\n'
path.write_text(text, encoding="utf-8")
PY
    log "upserted BROWSER_CDP_URL into $target"
  done < <(resolve_target_dotenvs)
}

# Strip BROWSER_CDP_URL from every dotenv we might have touched.
remove_hermes_dotenv_entry() {
  local target
  while IFS= read -r target; do
    [[ -n "$target" && -f "$target" ]] || continue
    HERMES_DOTENV_TARGET="$target" python3 - <<'PY'
import os, pathlib, re
path = pathlib.Path(os.environ["HERMES_DOTENV_TARGET"])
text = path.read_text(encoding="utf-8", errors="replace")
pattern = re.compile(r'^\s*(?:export\s+)?BROWSER_CDP_URL\s*=.*\n?', re.MULTILINE)
new = pattern.sub('', text)
if new != text:
    path.write_text(new, encoding="utf-8")
PY
    warn "stripped BROWSER_CDP_URL from $target (if present)"
  done < <(resolve_target_dotenvs)
}

self_check_ip() {
  local body country org
  if ! body="$(curl -fsS -m 8 https://ipinfo.io/json 2>/dev/null)"; then
    warn "ipinfo.io probe failed; skipping exit-IP self-check"
    return 0
  fi
  country="$(printf '%s' "$body" | python3 -c 'import json,sys;d=json.load(sys.stdin);print(d.get("country",""))' 2>/dev/null || true)"
  org="$(printf '%s' "$body" | python3 -c 'import json,sys;d=json.load(sys.stdin);print(d.get("org",""))' 2>/dev/null || true)"
  if [[ "$country" == "US" ]]; then
    log "exit OK: US via ${org:-unknown}"
  else
    warn "exit country = '${country:-?}' (org='${org:-?}') — NOT US. Check your VPN before running NA-only skills."
  fi
}

print_next_steps() {
  log "Chrome listening on http://127.0.0.1:$PORT"
  log "BROWSER_CDP_URL written to:"
  local target
  while IFS= read -r target; do
    [[ -n "$target" ]] && log "  - $target"
  done < <(resolve_target_dotenvs)
  log "  - $ENV_FILE            (sourceable, for ad-hoc shells)"
  log ""
  log ">>> RESTART your hermes API gateway once. After that, no manual export."
  log ""
  log "Invoke the skill with brief field:   browser_mode: local-chrome"
  log "  (set KOL_BROWSER_MODE=local-chrome on kol-ops-console backend"
  log "   to make every composed brief default to local-chrome)"
}

cmd_start() {
  [[ -x "$CHROME_BIN" ]] || die "Chrome binary not found at: $CHROME_BIN (override with DEBUG_CHROME_BIN)"

  local pids
  pids="$(port_pids)"
  if [[ -n "$pids" ]]; then
    if is_debug_chrome_ready; then
      warn "port $PORT already in use by debug Chrome (pids: $pids) — reusing"
      write_env_file || true
      self_check_ip
      print_next_steps
      return 0
    else
      die "port $PORT is in use by another process (pids: $pids). Free it first or set DEBUG_CHROME_PORT."
    fi
  fi

  mkdir -p "$PROFILE_DIR"
  log "starting Chrome (port=$PORT, profile=$PROFILE_DIR)"

  # Background, detached, swallow output. The Chrome window itself is the UI.
  "$CHROME_BIN" \
    --remote-debugging-port="$PORT" \
    --user-data-dir="$PROFILE_DIR" \
    --no-first-run \
    --no-default-browser-check \
    about:blank \
    >/dev/null 2>&1 &
  disown || true

  local waited=0
  while ! is_debug_chrome_ready; do
    sleep 1
    waited=$((waited + 1))
    if (( waited >= 15 )); then
      die "Chrome did not expose CDP on port $PORT within 15s"
    fi
  done

  write_env_file || warn "env file not written; you'll need to set BROWSER_CDP_URL manually"
  self_check_ip
  print_next_steps
}

cmd_status() {
  local pids
  pids="$(port_pids)"
  if [[ -z "$pids" ]]; then
    log "port $PORT: idle (no listener)"
  elif is_debug_chrome_ready; then
    log "port $PORT: debug Chrome ready (pids: $pids)"
    # Refresh the env file in case the browser id rotated.
    write_env_file || true
  else
    warn "port $PORT: occupied by non-debug process (pids: $pids)"
  fi
  if [[ -f "$ENV_FILE" ]]; then
    log "env file present: $ENV_FILE"
  else
    log "env file absent: $ENV_FILE"
  fi
  self_check_ip
}

# Emit a single `export BROWSER_CDP_URL=...` line to stdout so the caller can
# do:  eval "$(./start-debug-chrome.sh export)"
# All chatty output goes to stderr to keep stdout eval-safe.
cmd_export() {
  if ! is_debug_chrome_ready; then
    die "debug Chrome not ready on port $PORT — run './$(basename "$0")' first"
  fi
  local url
  if ! url="$(fetch_cdp_ws_url)"; then
    die "could not fetch webSocketDebuggerUrl from http://127.0.0.1:$PORT/json/version"
  fi
  printf 'export BROWSER_CDP_URL=%q\n' "$url"
}

cmd_stop() {
  local pids
  pids="$(port_pids)"
  if [[ -z "$pids" ]]; then
    log "nothing listening on port $PORT"
    remove_env_file
    return 0
  fi
  warn "killing pids on port $PORT: $pids"
  # shellcheck disable=SC2086
  kill $pids 2>/dev/null || true
  sleep 1
  pids="$(port_pids)"
  if [[ -n "$pids" ]]; then
    warn "still alive ($pids); sending SIGKILL"
    # shellcheck disable=SC2086
    kill -9 $pids 2>/dev/null || true
  fi
  remove_env_file
  log "stopped"
}

cmd_clean() {
  cmd_stop
  if [[ -d "$PROFILE_DIR" ]]; then
    warn "removing profile dir: $PROFILE_DIR"
    rm -rf "$PROFILE_DIR"
  else
    log "profile dir already absent: $PROFILE_DIR"
  fi
}

mode="${1:-start}"
case "$mode" in
  start)   cmd_start ;;
  status)  cmd_status ;;
  stop)    cmd_stop ;;
  restart) cmd_stop; cmd_start ;;
  clean)   cmd_clean ;;
  export)  cmd_export ;;
  *)       die "unknown mode: $mode (use: start|status|stop|restart|clean|export)" ;;
esac
