#!/usr/bin/env python3
"""Sync QuickCEP tag IDs into config/session_tag_map.yaml."""

from __future__ import annotations

import json
import os
import subprocess
import sys
from pathlib import Path

import yaml

_PLUGIN_ROOT = Path(__file__).resolve().parents[1]
_TAG_MAP = _PLUGIN_ROOT / "config" / "session_tag_map.yaml"
_DEFAULT_SKILL = Path.home() / ".hermes/profiles/povison-cs/skills/social-media/quickcep"

AI_TAG_NAMES = {
    "processing": "AI-处理中",
    "draft_ready": "AI-草稿待审",
    "awaiting_expert": "AI-待专家",
    "failed": "AI-处理失败",
    "closed": "AI-已结案",
}

INQUIRY_NAME_HINTS = {
    "logistics": ["in-transit", "shipping", "物流"],
    "product": ["pre-sale", "product", "售前"],
    "issue_standard": ["after-sale", "售后", "damage"],
    "refund_request": ["refund", "退款"],
    "b2b_inquiry": ["b2b", "wholesale"],
    "vip_discount": ["vip", "discount"],
    "unclear": ["other", "其他"],
}


def _quickcep_cli() -> Path:
    skill = Path(os.environ.get("CS_OPS_QUICKCEP_SKILL_DIR", str(_DEFAULT_SKILL)))
    return skill / "scripts" / "quickcep_cli.py"


def _fetch_tags_tree() -> list[dict]:
    cli = _quickcep_cli()
    if not cli.exists():
        raise SystemExit(f"quickcep_cli not found: {cli}")
    proc = subprocess.run(
        [sys.executable, str(cli), "tags-tree"],
        capture_output=True,
        text=True,
        timeout=120,
        cwd=str(cli.parent.parent),
    )
    if proc.returncode != 0:
        raise SystemExit(proc.stderr or proc.stdout)
    data = json.loads(proc.stdout)
    if isinstance(data, list):
        return data
    return data.get("tags") or data.get("data") or []


def _flatten_tags(groups: list[dict]) -> dict[str, str]:
    """Map lowercase tag name -> id."""
    out: dict[str, str] = {}

    def walk(node: dict) -> None:
        name = str(node.get("name") or "").strip()
        tid = node.get("id") or node.get("tagId")
        if name and tid:
            out[name.lower()] = str(tid)
        for child in node.get("children") or []:
            if isinstance(child, dict):
                walk(child)

    for group in groups:
        walk(group)
    return out


def _match_inquiry(flat: dict[str, str], hints: list[str]) -> str:
    for key, tid in flat.items():
        for hint in hints:
            if hint.lower() in key:
                return tid
    return ""


def main() -> None:
    groups = _fetch_tags_tree()
    flat = _flatten_tags(groups)

    tag_map: dict = {}
    if _TAG_MAP.exists():
        with _TAG_MAP.open(encoding="utf-8") as fh:
            tag_map = yaml.safe_load(fh) or {}

    ai = tag_map.setdefault("ai_lifecycle", {})
    for key, label in AI_TAG_NAMES.items():
        tid = flat.get(label.lower())
        if tid:
            ai[key] = tid
            print(f"AI lifecycle {label} -> {tid}")
        else:
            print(f"WARN: AI tag not found in QuickCEP: {label}")

    inquiry = tag_map.setdefault("inquiry_by_category", {})
    for cat, hints in INQUIRY_NAME_HINTS.items():
        tid = _match_inquiry(flat, hints)
        if tid:
            inquiry[cat] = tid
            print(f"Inquiry {cat} -> {tid}")

    _TAG_MAP.parent.mkdir(parents=True, exist_ok=True)
    with _TAG_MAP.open("w", encoding="utf-8") as fh:
        yaml.safe_dump(tag_map, fh, allow_unicode=True, sort_keys=False)
    print(f"Wrote {_TAG_MAP}")

    ref_path = _PLUGIN_ROOT / "config" / "tags-synced-reference.md"
    lines = ["# Tag IDs synced from QuickCEP", "", "Auto-generated by sync_session_tags.py.", ""]
    lines.append("## AI lifecycle")
    for key, label in AI_TAG_NAMES.items():
        lines.append(f"- {label} (`{key}`): `{ai.get(key, '')}`")
    lines.append("")
    lines.append("## Inquiry by category")
    for cat, tid in sorted(inquiry.items()):
        if tid:
            lines.append(f"- {cat}: `{tid}`")
    ref_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {ref_path}")


if __name__ == "__main__":
    main()
